### ISSUE TITLE
Dev build - HaCannotConnect: Initialization timed out

### ISSUE THREAD

**Issue by Garulf** [simbaja/gehome#24]
Component was working fine but now all I'm getting is:
```
2021-08-12 02:02:13 error (MainThread) [homeassistant.config_entries] Error setting up entry GE Home (3radication@gmail.com) for ge_home
Traceback (most recent call last):
  File "/Volumes/HomeAssistant/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
    await self.initialization_future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/HomeAssistant/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
    await self.initialization_future
  File "/Volumes/HomeAssistant/.venv/lib/python3.9/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/Volumes/HomeAssistant/.venv/lib/python3.9/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/HomeAssistant/.venv/lib/python3.9/site-packages/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/Volumes/HomeAssistant/custom_components/ge_home/__init__.py", line 26, in async_setup_entry
    if not await coordinator.async_setup():
  File "/Volumes/HomeAssistant/custom_components/ge_home/update_coordinator.py", line 174, in async_setup
    raise HaCannotConnect("Initialization timed out")
custom_components.ge_home.exceptions.HaCannotConnect: Initialization timed out
```

**Comment by Garulf** [comment]
Sorry, fixed the issue. The Air Conditioner had lost WiFi and had to be reset.
