### ISSUE TITLE
Could not obtain authorization code Error

### ISSUE THREAD

**Issue by agentcipher** [simbaja/gehome#62]
Trying to use the home assistant plugin and receiving the error below about not being able to obain an authorization code. It appears to be returning an HTML page as opposed to providing valid Oauth login information.  The username/password information are able to login using the SmartHQ app and the password does not contain any special characters, only letters and numbers.

$ gehome-appliance-data -u my_username -p my_password -r US
`Using slower stringprep, consider compiling the faster cython/libidn one.
2023-12-08 04:10:58,147 DEBUG    Using selector: EpollSelector
2023-12-08 04:10:58,148 DEBUG    Getting OAuth2 token
2023-12-08 04:10:58,148 DEBUG    received event: state_changed, processing callbacks...
2023-12-08 04:10:58,148 DEBUG    processing callback: <bound method GeBaseClient._on_state_change of <gehomesdk.clients.websocket_client.GeWebsocketClient object at 0x7f9e9a109490>>
2023-12-08 04:10:58,167 DEBUG    Client changed state: GeClientState.INITIALIZING to GeClientState.AUTHORIZING_OAUTH
2023-12-08 04:10:59,422 ERROR    There was a problem getting the authorization code, response details: {'method': 'POST', 'cookies': <SimpleCookie: abgea_region='us-east-1'>, '_real_url': URL('https://accounts.brillion.geappliances.com/oauth2/g_authenticate'), '_url': URL('https://accounts.brillion.geappliances.com/oauth2/g_authenticate'), '_body': b'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n<!DOCTYPE html>\n<html>\n<head>\n<title> OAuth Login</title>\n<meta name="format-detection" content="telephone=no"/>\n<meta charset="utf-8" />\n<meta http-equiv="X-UA-Compatible" content="IE=edge">\n\n\t<meta name="_csrf" content="64b9984b-e525-4825-a17e-42fa62a26188"/>\n\t<meta name="_csrf_header" content="X-CSRF-TOKEN"/>\n\n<meta name="viewport" content="width=device-width, initial-scale=1.0" />\n<meta name="description" content="" />\n<meta name="author" content="" />\n\n<link\n\thref="/resources/scripts/css/bootstrap.min.css"\n\trel="stylesheet" />\n<link\n\thref="/resources/scripts/css/desktop.css"\n\trel="stylesheet" />\n\n\t<link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700,900&display=swap"\n    \trel="stylesheet">\n<script\n\tsrc="/resources/scripts/jquery-3.5.1.min.js"></script>\n\n</head>\n\n\n\n\n\n<body>\n \n <div class="row">\n  <div class="col-md-3"></div><div class="col-md-6">\n \n \t\t        <nav class="navbar navbar-default navbar-static-top" id="custom-navbar custom-navbar-default" role="navigation">\n\t\t<div class="container">\n\t\t\t<div class="navbar-header" style="width: 100%;">\n\t\t\t<img src="/resources/scripts/images/SmartHQ_textlogo.png" class="img-responsive center-block">\n\n\n\t\t\t</div>\n\t\t</div>\n\t\t<nav class="navbarlogo navbarlogo-default navbar-static-top visible-sm visible-xs" id="custom-navbar-static-top" role="navigation">\n\t\t\t<div class="container">\n\t\t\t\t<div class="navbar-header" style="width: 100%">\n\t\t\t\t\t<div class="text-center app-logo" style="padding-left: 8px;">\n\t\t\t\t\t\t\n\t\t\t\t\t\t\t<img src="/resources/scripts/images/mobile_logo.png" class="img-responsive center-block">\n\t\t\t\t\t\t\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</nav>\n\t\t<nav class="navbarlogo navbarlogo-default navbar-static-top hidden-sm hidden-xs" id="custom-navbar-static-top"  role="navigation">\n\t\t\t<div class="container">\n\t\t\t\t<div class="navbar-header" style="width: 100%">\n\t\t\t\t\t<div class="text-center app-logo">\n\t\t\t\t\t\t\n\t\t\t\t\t\t\t<img src="/resources/scripts/images/mobile_logo.png" style="width: 358px;" class="img-responsive center-block">\n\t\t\t\t\t\t\n\t\t\t\t\t</div>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t</nav>\n\t</nav>\n\n\n\n\n\n\n\n\n\t    <div class="mainContainer">\n\t    <div class="line-divider"></div>\n\t  \n\t<div class="row">\n\t  <div class="col-md-2"></div>\n\t  <div class="col-md-8">\n          <div style="margin-bottom: 10px; text-align:center;">\n          \n                <h2>Sign In</h2>\n          \n                One account across our brands.<br/>\n          \n          </div>\n\n\n<br />\n<div class="alert alert-danger center" role="alert" id="alert_pane">\n\tInvalid Credentials\n\n</div>\n\n\n\n<div class="row" onKeyPress="return autoSubmit(event);">\n\t\n\t\t<form id="frmtimeout">\n\t\t\t\t<input type="hidden" id="client_id" value="564c31616c4f7474434b307435412b4d2f6e7672"\n\t\t\t\t\tname="client_id" />\n\t\t\t\t<input type="hidden" id="response_type" value="code"\n\t\t\t\t\tname="response_type" />\n\t\t\t\t<input type="hidden" id="access_type" value="offline"\n\t\t\t\t\tid="access_type" />\n\t\t</form>\n\t\t<form role="form" id="frmsignin" method="post">\n\t\t\t<div class="form-group">\n\t\t\t\t<input type="hidden" id="signature" name="signature"\n\t\t\t\t\tvalue="vVLoPdzS242Elr8Q7VEjLwtnFvSSY62MrSVnFTi69BfzV92DD8TQbdXqL8kKA5+JwdqYrppWFC6Np7APE6ubH3imNW7+CyPuI9P4fMLssZsSUJVNH3ATRpqxPhT+MBNGeFhaKIpBjFl3xD/mFzwe1BxwIUvVmyUpiy09qr/2Z4Arp8aWdGsMYy030Xs3EvnCERX2sP4byYqXYZCb5DPjBUwnFREnouETJBeTIOYf1SJlZbjd1vbDl3poynR7l/tsSyX70yz7E2SK/IeI3mEIjtcrlKSn8beo8Tvs+UY1/dnnGE0DCWYvm94E9J4JXTr3l7Zm7FVgD42iwJryItzrzfkk03x504Fn6CJpyAt+9L39JmZbJqiC0xqP+9+4jDqP39ZK9TNHbyM8bc0tmj5InMR71dpjs0DUBWEB82QjieV5TnHe0N0zNf0oA55R0/EDEtCWds1hhuYAzuWd3FUGP6GeED8ISvLYhXF2EspXTDrGNvIG8ct7XyvCHTs2WZNLPRfPwdpQz2roT7wCiY5VRQEwE6Jpj2Iq0LwaEJN6O0EmVCUHJ8gsrWiGNhUUEqgSeUfzyrP4zNPeEf828zzeXRUHHz4qbJNJqSka/243CMxQGhLp+PVsFR2IvTEkePoUre9fX4GaCZzwziFrrt8r3p3a8hhoXeELMQKVH+wdIu4/xtvBj1l4ITQ9DZ4JymzcAXt9q9xQQbsQCLCDS/WVL9qlJk4xu6laRTLuRBy0L8/HLN6nvHMgIK7JF2mUc9GiXm61uSzOgceTe8JMtHR4MwhaF7n5SPNBMzDZrmgEC5sABEGaMufbWfVxgXFbj7QhtLIDPQDidrDYNN2L49UuaMnDPW+i3UcymoWFX02MAg3MPzXim+EHC1Q8WulQ5xPNQMEFeOHR38J8lAqumhy/q3JiSJXuE8GmkpvbGre0P1EPtUO3C8oz4t8Vsep54GeK0KPkLhEKRdEVAPQy8ukXYMlyOPqPQuNGNMJoTnFgceLecFa+dLwqljWcDRMxDzGqDxbMlgaPOIUTkXO9wDUPlznwGifFwrpCSYcQtpQIF4XvP34RFblabtKp58pUnYczXSoqjbZGonbHZR0ULvAXKCif2CX+uttLMKtXJrKivSOq/Hz0R308qZMECHLf6u+VtifjZoBDsTIaSI8S96oxKEFmQpKOAXDnIeBwt+DgMz0Bh655bMnYBkIm7kxqB/YyZWkqQZsBuzxeajtrUBhmxP67Mn9L3SIM0GrqRVP3NtV2PDNGCFzs4wQP4o9Mql8FrjDJytQUtcuHOCmTbmXjP63xcpazw/umVbFxexkHJ/IoNfpAUKoiHSzKMkW7rLP7HAHpANM4Fs4IurURrqj7SpL0I7Ff3I0EqEGQ/sZGZ1Gg2o/nhXbNyX3xQHB8J9Y/0pgm8iagXpKcRtxPxyOsecchiiRmHf1x8G2pIxsvOOMJJ8sRiuN/BmdemQQ+n+nNr/tWqyF8xaSgBJLZNqb80Jz3mzDKH6jzriebkvxd8rwyKmb+Qh35Ia0J1G3FYkaw80BR/yasyrTx/xMQNUo1C64PgdFvmZNtDwG0WmAsVggBbpPp3ztIwfr68yE+d6pdGlPskBd99YUcjrCb8rWUZgdC137QSNXLv/fLtuu3CIo63dbGLwrMIMyEUoRmRilM5ESjSv/M+DSRC2stJTCxIenm9mcMpvjCjDyO0xSSDxsLXPvKQ6NoqFe9ansJs7FDs6UCPTwP99FWDnGMS8SikFItQeX0FAq5it0z3bxoO1L2kgSHGpEgnNC1G08tfQ1Qb27QHYXjN2fcWa17/yYStXKU/fVzIJZFdhlAiUD5xAbkFCnPZh+PSiYUuvn6gYOd5JyC0fBSR3dOQNM39ujTOuv0ZWiiXLtto+2oZBCJVKaM3EhYIKzjFE4dSJxCL+CPK+XgeTACpiuyzhYHNWHOBstPvv8j+vGGWktQifXXspzT2S2lpDwKrRFt0lHXGCnxHdoiZSuGCPL2j7TmOBvxaiAFuDS7gWwUCmuhqoIQ0iyTQNhqs4tkP91/jOPy+d+uMXf/MF/ef4Ue/m0/FtrZXdSitphZ9RVVnpmqgL5IDz76EsrVah88C+0xRCTr76BlGswa59azeBRCZ9HZh/6BqOkEQID2ciAWaCxYqCXUiNci/c+/p57d096qW1iGN65XeopXgRqbdP2d2wxmq0nDHYEPylI38SYXUwOO2huF6ZJ95u8wau7GZFAcYp0rW9DIZ3yQu/UYXt9WrGASOAVNSfk5mnL4aEKZBx7hIgRYuBWeNmOhBMgSPEg3N7LpKfnNebW5VEcApm1D3JESYKToxw==" />\n\t\t\t</div>\n\t\t\t<div class="form-group" id="grp_username">\n\t\t\t\t<input type="email" class="form-control" id="username"\n\t\t\t\t\tname="username" placeholder="Username" autocapitalize="off"\n\t\t\t\t\tvalue="my_username" tabindex="1" />\n\t\t\t\t<div class="error_message" id="error_username"></div>\n\t\t\t</div>\n\t\t\t<div class="form-group" id="grp_password">\n\t\t\t\t<input type="password" class="form-control" id="password"\n\t\t\t\t\tname="password" placeholder="Password" tabindex="2" maxlength="20" />\n\t\t\t\t<input type="checkbox" id="showHide"> Show Password <br>\n\t\t\t\t<div class="error_message" id="error_password"></div>\n\t\t\t</div>\n\t\t\t\n\t\t\t<div class="form-group">\n\t\t\t\t<a href="#" onclick="javascript:forgotPassword()" tabindex="6">\n\t\t\t\t\tForgot your password? \n\t\t\t\t</a>\n\t\t\t</div>\n\t\t\t<div class="form-group" style="padding:10px;">\n\t\t\t<button type="button" id="signin_btn" name="signin_btn" class="btn_signIn btn btn-default btn-primary"\n\t\t\t\tonClick="javascript:oauthLogin()" tabindex="4">\n\t\t\t\t\tSIGN IN\n\t\t\t\t</button>\n\t\t\t</div>\n\t\t\t<div class="row">\n\t\t\t\t\t<div class="col-md-12" align="center" >\n\t\t\t\t\t\t\t<h6 style="font-weight: 100px;font-size: 12px;">\n\n\t\t\t\t\t\t\t\tIf you have a European or United Kingdom account,\n\n\t\t\t\t\t\t\t\t<a href="#" onClick="javascript:oAuthChangeLoginRegion()">\n\t\t\t\t\t\t\t\t\t<u>\n\t\t\t\t\t\t\t\t\t\tsign in here\n\t\t\t\t\t\t\t\t\t</u>\n\t\t\t\t\t\t\t\t</a>\n\t\t\t\t\t\t\t</h6>\n\n\t\t\t\t\t</div>\n\t\t\t</div>\n\n\t\t\t<div class="overlay" id="overlay">\n                        <div class="loader" id="loader"></div>\n                    </div>\n            <div class="row">\n\t\t\t\t<div class="col-md-2"></div>\n\t\t\t\t\t<div class="col-md-8" align="center" >\n\t\t\t\t\t\t\t<h6 style="font-weight: 100px;font-size: 12px;margin-top: 10px;">Don\'t have an account?<a id="link-register" href="#" onClick="javascript:register()">&nbsp;<u>Sign up here</u></a></h6>\n\n\t\t\t\t\t</div>\n\t\t\t\t<div class="col-md-2"></div>\n\t\t\t</div>\n\t\t\t<input type="hidden" name="_csrf" value="64b9984b-e525-4825-a17e-42fa62a26188" />\n\t\t</form>\n</div>\n\n\n<script type="text/javascript">\nvar initialTime = new Date();\nvar refreshIntervalId;\nvar checkSessionTimeout = function () {\n    var milliseconds = Math.abs((initialTime - new Date()));\n    if (milliseconds > 870000) {\n    \tif (refreshIntervalId) {\n    \t\tclearInterval(refreshIntervalId);\n    \t}\n    \t$("#frmtimeout").attr("action",\n\t\t"/oauth2/timeout");\n\t\t$("#frmtimeout").submit();\n    }\n};\n\n$(document).ready(function() {\n\t$("#showHide").click(function () {\n\t\tif ($("#showHide").is(":checked")) {\n\t\t$("#password").attr("type", "text");\n\t\t}\n\t\telse{\n\t\t$("#password").attr("type", "password");\n\t\t}\n\t\t});\n\t\trefreshIntervalId = setInterval(checkSessionTimeout, 10000);\n });\n\n</script>\n\n\n\n\n<script type="text/javascript">\n    var submitted = false;\n\tvar RX = {\n\t\t\tEMAIL:             /^\\s*(\\w+(?:(?:-\\w+)|(?:\\.\\w+)|(?:\\+\\w+))*\\@[A-Za-z0-9]+(?:(?:\\.|-)[A-Za-z0-9]+)*\\.[A-Za-z0-9][A-Za-z0-9]+)\\s*$/\n\t};\n\tvar RX_NORMALIZE = {\n\t\t\tEMAIL: "$1"\n\t};\n\tfunction validateEmail (email, test, normalize) {\n\t\tif (!test.test(email)) {\n\t\t\t\treturn false;\n\t\t}\n\t\treturn true;\n\t}\n\tfunction autoSubmit(e) {\n\t\tvar key;\n\n\t\tif (window.event)\n\t\t\tkey = window.event.keyCode; //IE\n\t\telse\n\t\t\tkey = e.which; //firefox\n\n\t\tif (key == 13) {\n\t\t\toauthLogin();\n\t\t\treturn false;\n\t\t} else {\n\t\t\treturn true;\n\t\t}\n\t}\n\n\tfunction oAuthChangeLoginRegion() {\n\t\tdocument.location.href="https://accounts.brillion.geappliances.com/oauth2/auth?client_id=564c31616c4f7474434b307435412b4d2f6e7672&response_type=code&redirect_uri=brillion.4e617a766474657344444e562b5935566e51324a%3A%2F%2Foauth%2Fredirect&access_type=offline&region=eu";\n\t}\n\n\tfunction oauthLogin() {\n\t\tif (submitted) {\n\t\t\treturn;\n\t\t}\n\t\tsubmitted = true;\n\t\tvar elmFocus = null;\n\t\tif ($("#username").val() == \'\') {\n\t\t\t//$("#error_username").html("Enter username");\n\t\t\t$("#error_username").html("Enter username");\n\t\t\t$("#grp_username").addClass("has-error");\n\t\t\telmFocus = $("#username");\n\t\t} else {\n\t\t\t$("#error_username").html("");\n\t\t\t$("#grp_username").removeClass("has-error");\n\t\t}\n\n\t\tif (!validateEmail ($("#username").val(), RX.EMAIL, RX_NORMALIZE.EMAIL)) {\n\t\t\t//$("#error_username").html("Invalid email address");\n\t\t\t$("#error_username").html("Invalid email address");\n\t\t\t$("#grp_username").addClass("has-error");\n\t\t\telmFocus = $("#username");\n\t\t} else {\n\t\t\t$("#error_username").html("");\n\t\t\t$("#grp_username").removeClass("has-error");\n\t\t}\n\n\t\t$("#username").val( $("#username").val().replace(RX.EMAIL, RX_NORMALIZE.EMAIL));\n\n\t\tif ($("#password").val() == \'\') {\n\t\t\t//$("#error_password").html("Enter password");\n\t\t\t$("#error_password").html("Enter password");\n\t\t\t$("#grp_password").addClass("has-error");\n\t\t\tif (elmFocus == null) {\n\t\t\t\telmFocus = $("#password");\n\t\t\t}\n\t\t} else {\n\t\t\t$("#error_password").html("");\n\t\t\t$("#grp_password").removeClass("has-error");\n\t\t}\n\n\n\t\tif (elmFocus != null) {\n\t\t\telmFocus.focus();\n\t\t\tsubmitted = false;\n\t\t\treturn;\n\t\t}\n\t\t$("#frmsignin").attr("action",\n\t\t\t\t"/oauth2/g_authenticate");\n\t\t$("#frmsignin").submit();\n\t\t$("#overlay").css({"display":"block"});\n\t}\n\n\tfunction resend() {\n\t\t$("#frmresend").attr("action",\n\t\t"/resend");\n\t\t$("#frmresend").submit();\n\t}\n\n\tfunction register() {\n\n\t\t\tdocument.location.href = \'/account/register\';\n\n\t}\n\n\tfunction forgotPassword() {\n\t\tdocument.location.href = \'/consumer/forgotpwd/display\';\n\t}\n\n\tfunction showRecaptcha() {\n\t\tRecaptcha.create("",\n\t\t\t\t\'captchadiv\', {\n\t\t\t\t\tcallback : Recaptcha.focus_response_field\n\t\t\t\t});\n\t}\n\n\tfunction getCaptchaText() {\n\t\treturn $(\'#captchadiv\').find(\'[name="recaptcha_response_field"]\').val();\n\t}\n\n\tfunction showCaptchaData() {\n\t\tvar capData = "<p>recaptcha_challenge_field</p>";\n\t\tcapData += "<p>"\n\t\t\t\t+ $(\'#captchadiv\').find(\'[name="recaptcha_challenge_field"]\')\n\t\t\t\t\t\t.val() + "</p>";\n\t\tcapData += "<p>recaptcha_response_field</p>";\n\t\tcapData += "<p>"\n\t\t\t\t+ $(\'#captchadiv\').find(\'[name="recaptcha_response_field"]\')\n\t\t\t\t\t\t.val() + "</p>";\n\n\t\t$(\'#captchadiv2\').html(capData);\n\t}\n\n\n</script>\n\n\n\t\n\n\n</div>\n\t\t<div class="col-md-2"></div>\n\t</div>\n\n\t\n        \t        <br>\n        \t        <div class="line-divider"></div>\n                    <div class="row">\n                          <div class="col-md-2"></div>\n                          <div class="col-md-8">\n                                <p style="font-weight: 50; font-size: 10px; letter-spacing: 0.02em;">\n                                    Copyright 2020 GE Appliances, a Haier company GE is trademark of General Electric Company.Manufactured under trademark license.\n                                </p>\n                          </div>\n                    </div>\n                    </div>\n                    </div>\n        \t  \n\t</div>\n\n\r\n\r\n\r\n\r\n\r\n\r\n<footer class="wca-footer">\r\n\t<div class="container">\r\n\t\t<p class="text-muted">\r\n\t\t\t\t<a class="nowrap" href="javascript:launch(\'https://static.brillion.geappliances.com/policies/eula.html\')">Terms</a>&#160; |  \r\n\t\t\t\t&#160;<a class="nowrap" href="javascript:launch(\'https://static.brillion.geappliances.com/policies/privacy_policy.html\')">Privacy</a>&#160;\t|\r\n\t\t\t\t&#160;<a class="nowrap" href="javascript:launch(\'https://www.geappliances.com/privacy/privacy_policy.htm#californiaPrivacyNotice\')">California Privacy Notice</a>&#160;\t|\r\n\t\t\t\t&#160;<a class="nowrap" href="javascript:launch(\'https://www.geappliances.com/privacy/privacy_policy.htm#OptOutOptIn\')">Do Not Sell or Share my Personal Information</a>&#160;\t|\r\n\t\t\t\t&#160;<a class="nowrap" href="javascript:launch(\'https://www.geappliances.com/accessibility-statement/\')">Accessibility</a>&#160;\t\r\n\t\t\t\r\n\t\t</p>\r\n\r\n\t</div>\r\n</footer>\r\n\r\n\r\n\r\n<script\r\n\tsrc="/resources/scripts/js/bootstrap.min.js"></script>\r\n<script\r\n\tsrc="/resources/scripts/js/bootstrap-show-password.min.js"></script>\r\n<script\r\n\tsrc="/resources/scripts/common.js"></script>\r\n</body>\r\n</html>\r\n\r\n\r\n\n\n', '_writer': None, '_continue': None, '_closed': True, '_history': (), '_request_info': RequestInfo(url=URL('https://accounts.brillion.geappliances.com/oauth2/g_authenticate'), method='POST', headers=<CIMultiDictProxy('Host': 'accounts.brillion.geappliances.com', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.11 aiohttp/3.8.5', 'Cookie': 'JSESSIONID=64DDC436124E8D9E0EF2E50693432133; abgea_region=us-east-1', 'Content-Length': '2615', 'Content-Type': 'application/x-www-form-urlencoded')>, real_url=URL('https://accounts.brillion.geappliances.com/oauth2/g_authenticate')), '_timer': <aiohttp.helpers.TimerContext object at 0x7f9e9a11f850>, '_cache': {'headers': <CIMultiDictProxy('Content-Type': 'text/html;charset=ISO-8859-1', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Fri, 08 Dec 2023 04:10:59 GMT', 'X-Amzn-Trace-Id': 'Root=1-65729752-5f8b75295d889aa330bb0b87;', 'Set-Cookie': 'abgea_region=us-east-1; Path=/; Secure; HttpOnly', 'X-Frame-Options': 'DENY', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 d775d0025d4d26af03f89c82cea6813e.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ATL58-P4', 'X-Amz-Cf-Id': '9MAp66YCJrrJPd157ejawBvAGZ_u-nhpzPr9PCM2MjcFqwN1Bjzt1w==')>, 'url': URL('https://accounts.brillion.geappliances.com/oauth2/g_authenticate')}, '_traces': [], '_loop': <_UnixSelectorEventLoop running=True closed=False debug=False>, '_session': None, '_protocol': <aiohttp.client_proto.ResponseHandler object at 0x7f9e9a0e25f0>, '_connection': None, 'version': HttpVersion(major=1, minor=1), 'status': 200, 'reason': '', '_headers': <CIMultiDictProxy('Content-Type': 'text/html;charset=ISO-8859-1', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Fri, 08 Dec 2023 04:10:59 GMT', 'X-Amzn-Trace-Id': 'Root=1-65729752-5f8b75295d889aa330bb0b87;', 'Set-Cookie': 'abgea_region=us-east-1; Path=/; Secure; HttpOnly', 'X-Frame-Options': 'DENY', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 d775d0025d4d26af03f89c82cea6813e.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ATL58-P4', 'X-Amz-Cf-Id': '9MAp66YCJrrJPd157ejawBvAGZ_u-nhpzPr9PCM2MjcFqwN1Bjzt1w==')>, '_raw_headers': ((b'Content-Type', b'text/html;charset=ISO-8859-1'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Fri, 08 Dec 2023 04:10:59 GMT'), (b'X-Amzn-Trace-Id', b'Root=1-65729752-5f8b75295d889aa330bb0b87;'), (b'Set-Cookie', b'abgea_region=us-east-1; Path=/; Secure; HttpOnly'), (b'X-Frame-Options', b'DENY'), (b'X-Content-Type-Options', b'nosniff'), (b'X-XSS-Protection', b'1; mode=block'), (b'Cache-Control', b'no-cache, no-store, max-age=0, must-revalidate'), (b'Pragma', b'no-cache'), (b'Expires', b'0'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 d775d0025d4d26af03f89c82cea6813e.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'ATL58-P4'), (b'X-Amz-Cf-Id', b'9MAp66YCJrrJPd157ejawBvAGZ_u-nhpzPr9PCM2MjcFqwN1Bjzt1w==')), 'content': <StreamReader eof>}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gehomesdk/clients/async_login_flows.py", line 76, in async_get_authorization_code
    code = await async_handle_ok_response(session, await resp.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gehomesdk/clients/async_login_flows.py", line 111, in async_handle_ok_response
    raise GeAuthFailedError(f"Authentication failed, reason: {reason}")
gehomesdk.exception.ge_auth_failed_error.GeAuthFailedError: Authentication failed, reason: Invalid Credentials
2023-12-08 04:10:59,423 ERROR    Task exception was never retrieved
future: <Task finished name='Task-1' coro=<GeBaseClient.async_get_credentials_and_run() done, defined at /usr/local/lib/python3.11/site-packages/gehomesdk/clients/base_client.py:117> exception=GeAuthFailedError('Could not obtain authorization code')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gehomesdk/clients/async_login_flows.py", line 76, in async_get_authorization_code
    code = await async_handle_ok_response(session, await resp.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gehomesdk/clients/async_login_flows.py", line 111, in async_handle_ok_response
    raise GeAuthFailedError(f"Authentication failed, reason: {reason}")
gehomesdk.exception.ge_auth_failed_error.GeAuthFailedError: Authentication failed, reason: Invalid Credentials

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gehomesdk/clients/base_client.py", line 119, in async_get_credentials_and_run
    await self.async_get_credentials(session)
  File "/usr/local/lib/python3.11/site-packages/gehomesdk/clients/base_client.py", line 191, in async_get_credentials
    await self.async_do_full_login_flow()
  File "/usr/local/lib/python3.11/site-packages/gehomesdk/clients/base_client.py", line 195, in async_do_full_login_flow
    self.credentials = await self._async_do_full_login_flow()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gehomesdk/clients/websocket_client.py", line 63, in _async_do_full_login_flow
    await self._async_get_oauth2_token()
  File "/usr/local/lib/python3.11/site-packages/gehomesdk/clients/base_client.py", line 218, in _async_get_oauth2_token
    oauth_token = await async_get_oauth2_token(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gehomesdk/clients/async_login_flows.py", line 147, in async_get_oauth2_token
    code = await async_get_authorization_code(session, account_username, account_password, account_region)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gehomesdk/clients/async_login_flows.py", line 83, in async_get_authorization_code
    raise GeAuthFailedError(f'Could not obtain authorization code') from exc
gehomesdk.exception.ge_auth_failed_error.GeAuthFailedError: Could not obtain authorization code`

**Comment by simbaja** [comment]
Not sure why it wouldn't work, only things I can think of are the region is incorrect or you might need to enclose your username/password in single quotes?

**Comment by agentcipher** [comment]
To prevent future pain and suffering for someone else.  The issue in this case appears to be that my password was too long🤦

**Comment by simbaja** [comment]
What is the max length, I can add that to the stickied posts?
