### ISSUE TITLE
gehome-appliance-data : RuntimeError: no running event loop

### ISSUE THREAD

**Issue by mguaylam** [simbaja/gehome#72]
I'm trying to run gehome-appliance-data to read what's happening on the API but after installing it I get :
```Using slower stringprep, consider compiling the faster cython/libidn one.
2024-09-21 20:26:51,409 DEBUG    Using selector: EpollSelector
Traceback (most recent call last):
  File "/home/mguaylam/.local/bin/gehome-appliance-data", line 8, in <module>
    sys.exit(appliance_data())
             ^^^^^^^^^^^^^^^^
  File "/home/mguaylam/.local/lib/python3.12/site-packages/gehomesdk/entry_points.py", line 18, in appliance_data
    gather_appliance_data(args.username, args.password, args.region)
  File "/home/mguaylam/.local/lib/python3.12/site-packages/gehomesdk/gather_data.py", line 54, in gather_appliance_data
    session = aiohttp.ClientSession()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mguaylam/.local/lib/python3.12/site-packages/aiohttp/client.py", line 294, in __init__
    loop = loop or asyncio.get_running_loop()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
```
I did supply my username, password and region.
Would anyone know if i'm missing something?

Thank you for your help.

**Comment by Jason-nz** [comment]
Looks like a breaking change in aiohttp 3.10.0 

https://github.com/aio-libs/aiohttp/issues/8555

**Comment by Jason-nz** [comment]
Try pip install aiohttp==3.9.5 
That should get it working
